name: Code Checks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyTelegrambotApi
          python -m pip install flake8
      - name: Run flake8
        run: flake8 .
